
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hadoop
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        btnAddEnv.setEnabled(false);
        btnHadoopEnvSetup.setEnabled(false);
        btnCoreSiteSetup.setEnabled(false);
        btnHdfsSiteSetup.setEnabled(false);
        btnMakeDirectory.setEnabled(false);
        btnCopyMapred.setEnabled(false);
        btnMapredSiteSetup.setEnabled(false);
        btnYarnSiteSetup.setEnabled(false);
       // btnFormatNameNode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUntarHadoop = new javax.swing.JButton();
        btnAddEnv = new javax.swing.JButton();
        btnHadoopEnvSetup = new javax.swing.JButton();
        btnCoreSiteSetup = new javax.swing.JButton();
        btnHdfsSiteSetup = new javax.swing.JButton();
        btnMakeDirectory = new javax.swing.JButton();
        btnCopyMapred = new javax.swing.JButton();
        btnMapredSiteSetup = new javax.swing.JButton();
        btnYarnSiteSetup = new javax.swing.JButton();
        btnFormatNameNode = new javax.swing.JButton();
        btnStartStop = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Hadoop User");

        btnUntarHadoop.setText("Untar Hadoop");
        btnUntarHadoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUntarHadoopActionPerformed(evt);
            }
        });

        btnAddEnv.setText("Add Envir");
        btnAddEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnvActionPerformed(evt);
            }
        });

        btnHadoopEnvSetup.setText("Hadoop Env Set");
        btnHadoopEnvSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHadoopEnvSetupActionPerformed(evt);
            }
        });

        btnCoreSiteSetup.setText("Core Site Setup");
        btnCoreSiteSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoreSiteSetupActionPerformed(evt);
            }
        });

        btnHdfsSiteSetup.setText("HDFS Site Setup");
        btnHdfsSiteSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHdfsSiteSetupActionPerformed(evt);
            }
        });

        btnMakeDirectory.setText("Make Directory");
        btnMakeDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeDirectoryActionPerformed(evt);
            }
        });

        btnCopyMapred.setText("Copy Mapred ");
        btnCopyMapred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyMapredActionPerformed(evt);
            }
        });

        btnMapredSiteSetup.setText("Mapred Site Setup");
        btnMapredSiteSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapredSiteSetupActionPerformed(evt);
            }
        });

        btnYarnSiteSetup.setText("Yarn Site Setup");
        btnYarnSiteSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYarnSiteSetupActionPerformed(evt);
            }
        });

        btnFormatNameNode.setText("Format Name Node");
        btnFormatNameNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatNameNodeActionPerformed(evt);
            }
        });

        btnStartStop.setText("start and stop");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnYarnSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCopyMapred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHdfsSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btnHadoopEnvSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUntarHadoop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCoreSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMakeDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMapredSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFormatNameNode, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUntarHadoop, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHadoopEnvSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnCoreSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHdfsSiteSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnMakeDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMapredSiteSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopyMapred, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYarnSiteSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFormatNameNode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUntarHadoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUntarHadoopActionPerformed
        UntarHadoop u = new UntarHadoop();
        u.untarHadoop();
        btnAddEnv.setEnabled(true);
        btnUntarHadoop.setEnabled(false);

    }//GEN-LAST:event_btnUntarHadoopActionPerformed

    private void btnAddEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnvActionPerformed
        AddEnv a = new AddEnv();
        a.addEnv();
        btnHadoopEnvSetup.setEnabled(true);
        btnAddEnv.setEnabled(false);
    }//GEN-LAST:event_btnAddEnvActionPerformed

    private void btnHadoopEnvSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHadoopEnvSetupActionPerformed
        HadoopEnvSetup h = new HadoopEnvSetup();
        h.hadoopEnvSetup();
        btnCoreSiteSetup.setEnabled(true);
        btnHadoopEnvSetup.setEnabled(false);
    }//GEN-LAST:event_btnHadoopEnvSetupActionPerformed

    private void btnCoreSiteSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoreSiteSetupActionPerformed
        CoreSiteSetup c = new CoreSiteSetup();
        c.coreSiteSetup();
        btnHdfsSiteSetup.setEnabled(true);
        btnCoreSiteSetup.setEnabled(false);
    }//GEN-LAST:event_btnCoreSiteSetupActionPerformed

    private void btnHdfsSiteSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHdfsSiteSetupActionPerformed
        HdfsSiteSetup h = new HdfsSiteSetup();
        h.hdfsSiteSetup();
        btnMakeDirectory.setEnabled(true);
        btnHdfsSiteSetup.setEnabled(false);
    }//GEN-LAST:event_btnHdfsSiteSetupActionPerformed

    private void btnMakeDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeDirectoryActionPerformed
        PrMkDir p = new PrMkDir();
        p.mkDir();
        btnCopyMapred.setEnabled(true);
        btnMakeDirectory.setEnabled(false);
    }//GEN-LAST:event_btnMakeDirectoryActionPerformed

    private void btnCopyMapredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyMapredActionPerformed
        CopyMapredSite c = new CopyMapredSite();
        c.copyMapredSite();
        btnMapredSiteSetup.setEnabled(true);
        btnCopyMapred.setEnabled(false);
    }//GEN-LAST:event_btnCopyMapredActionPerformed

    private void btnMapredSiteSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapredSiteSetupActionPerformed
        MapredSiteSetup m = new MapredSiteSetup();
        m.mapredSiteSetup();
        btnYarnSiteSetup.setEnabled(true);
        btnMapredSiteSetup.setEnabled(false);
    }//GEN-LAST:event_btnMapredSiteSetupActionPerformed

    private void btnYarnSiteSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYarnSiteSetupActionPerformed
        YarnSiteSetup y = new YarnSiteSetup();
        y.yarnSiteSetup();
        btnFormatNameNode.setEnabled(true);
        btnYarnSiteSetup.setEnabled(false);
    }//GEN-LAST:event_btnYarnSiteSetupActionPerformed

    private void btnFormatNameNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatNameNodeActionPerformed
        FormatNameNode f = new FormatNameNode();
        f.formatNameNode();
        btnStartStop.setEnabled(true);
        btnFormatNameNode.setEnabled(false);
    }//GEN-LAST:event_btnFormatNameNodeActionPerformed

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        JOptionPane.showMessageDialog(this, "start-all.sh command for start the all services,stop-all.sh command for stop the services and jps command is used to view all hadoop services");
    }//GEN-LAST:event_btnStartStopActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEnv;
    private javax.swing.JButton btnCopyMapred;
    private javax.swing.JButton btnCoreSiteSetup;
    private javax.swing.JButton btnFormatNameNode;
    private javax.swing.JButton btnHadoopEnvSetup;
    private javax.swing.JButton btnHdfsSiteSetup;
    private javax.swing.JButton btnMakeDirectory;
    private javax.swing.JButton btnMapredSiteSetup;
    private javax.swing.JButton btnStartStop;
    private javax.swing.JButton btnUntarHadoop;
    private javax.swing.JButton btnYarnSiteSetup;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
